version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      # Insert steps here that will build your project, see detailed Circle CI 2.0 instructions:
      # https://circleci.com/docs/2.0/language-java/  
      - deploy:
          command: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle2/scripts/upload)
